# Generated by Django 4.2.1 on 2023-11-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('region1', models.CharField(max_length=255)),
                ('region2', models.CharField(max_length=255)),
            ],
        ),
    ]
